Repository Jagroop2001/AcmeRockets, pull requests merged in 2024-01, with the labels that each got.

#15 Added form backend
  build/index.html
Labels: JWOC, Medium

#28 Added Light and Dark toggle button
  build/css/style.css
  build/index.html
  build/js/main.js
  tailwind.config.js
Labels: JWOC, Medium

#21 Now fixed index.html and style.css for footer
  build/css/style.css
  build/index.html
Labels: JWOC, Medium

#35 Redesigned the footer
  build/index.html
Labels: JWOC, Hard

#36 fix/scrollbar
  src/input.css
Labels: JWOC, Easy

#39 gototop button feature added
  build/css/style.css
  build/index.html
  build/js/GoToTop.js
Labels: JWOC, Medium

#43 added changes
  build/css/feedback.css
  build/feedback.html
  build/img/astronaut-cartoon-floating-in-space.jpg
  build/index.html
Labels: JWOC, Hard

#52 made the changes
  build/css/testimonial.css
Labels: JWOC, Hard

#51 Revamp
  README.md
  documentation_source/contact.png
  documentation_source/contribution/clone.png
  documentation_source/contribution/fork.png
  documentation_source/products.png
  documentation_source/responsive.png
  documentation_source/testimonials.png
  documentation_source/website.png
Labels: JWOC, Hard

#58 Contributor page added
  build/contributor.css
  build/contributor.html
  build/contributor.js
  build/index.html
Labels: JWOC, Hard

#49 About us section
  build/css/style.css
  build/img/rocket.webp
  build/index.html
  package-lock.json
Labels: JWOC, Medium

#67 Added underline hover effect. Fixes #59
  build/index.html
Labels: JWOC, Easy

#68 Change color in the slider Fixed #64
  build/css/style.css
  build/css/testimonial.css
  build/index.html
Labels: JWOC, Easy
