Repository Jagroop2001/AcmeRockets, pull requests merged in 2024-03, with the labels that each got.

#116 [FIX]:navigation bar typo
  .vscode/settings.json
  build/index.html
Labels: Easy, Woc

#121 feat: improved footer design
  .prettierrc
  build/css/style.css
  build/index.html
  package-lock.json
  src/input.css
  tailwind.config.js
Labels: Hard, Woc

#125 added smooth scrolling functionality
  build/css/style.css
  build/index.html
  build/js/smoothScroll.js
Labels: Medium, Woc
